name: tachidesk_flutter
version: 0.1.0+1
publish_to: none
description: A new Flutter frontend for Tachidesk flutter.
environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'

dependencies:
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  get: 4.6.1
  get_storage: ^2.0.3
  grouped_list: ^4.1.0
  intl: ^0.17.0
  readmore: ^2.1.0
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
