name: tachidesk_sorayomi
version: 0.2.1+1
publish_to: none
description: A new Flutter frontend for Tachidesk.
environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.3.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  font_awesome_flutter: ^10.1.0
  get: 4.6.1
  get_storage: ^2.0.3
  grouped_list: ^4.1.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  package_info_plus: ^1.4.0
  path: ^1.8.1
  path_provider: ^2.0.9
  pub_semver: ^2.1.1
  readmore: ^2.1.0
  scrollable_positioned_list: ^0.2.3
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  lints: 2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
